export const styles = {
  page: {
    background: "#0f0e0c",
    minHeight: "100vh",
    padding: "3rem 1rem",
    fontFamily: "'Jost', sans-serif",
    fontWeight: 300,
    color: "#e8e0d0",
  },
  inner: {
    maxWidth: 560,
    margin: "0 auto",
  },
  masthead: {
    textAlign: "center",
    paddingBottom: "2.5rem",
    borderBottom: "0.5px solid #2e2b25",
  },
  cafeName: {
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: 52,
    fontWeight: 300,
    letterSpacing: 10,
    color: "#e8e0d0",
    lineHeight: 1,
  },
  tagline: {
    fontSize: 11,
    letterSpacing: 4,
    color: "#6b6456",
    marginTop: 10,
    textTransform: "uppercase",
  },
  info: {
    fontSize: 11,
    color: "#4a4640",
    marginTop: 6,
    letterSpacing: 1,
  },
  section: {
    padding: "2rem 0",
    borderTop: "0.5px solid #1e1c18",
  },
  sectionTitle: {
    fontSize: 10,
    letterSpacing: 5,
    color: "#6b6456",
    textTransform: "uppercase",
    marginBottom: "1.5rem",
  },
  item: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: "1rem",
    padding: "10px 0",
    borderTop: "0.5px solid #1a1916",
  },
  itemFirst: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: "1rem",
    padding: "10px 0",
  },
  itemLeft: { flex: 1 },
  itemName: {
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: 19,
    fontWeight: 400,
    color: "#e8e0d0",
    lineHeight: 1.2,
  },
  itemSub: {
    fontStyle: "italic",
    fontWeight: 300,
    color: "#b0a898",
    fontSize: 16,
  },
  itemNote: {
    fontSize: 11,
    color: "#4a4640",
    marginTop: 3,
    letterSpacing: 0.5,
    lineHeight: 1.5,
  },
  itemPrice: {
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: 16,
    color: "#b0a898",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  footer: {
    textAlign: "center",
    paddingTop: "2.5rem",
    borderTop: "0.5px solid #2e2b25",
    fontSize: 11,
    color: "#4a4640",
    letterSpacing: 1.5,
    lineHeight: 2,
  },
};